-- Search/display tags generated by a cheap utility model call and editable by
-- the user. Stored as a JSON array of strings.
ALTER TABLE courses ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE roadmaps ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
